/* ORDER BY */
SELECT
       MENU_CODE
	  ,MENU_NAME
	  ,MENU_PRICE
  FROM TBL_MENU
 -- ORDER BY MENU_PRICE ASC; --오름차순ASC는 사실 빼도 된다 
 ORDER BY MENU_PRICE ASC;
 
 SELECT
       MENU_CODE
	  ,MENU_NAME
	  ,MENU_PRICE
  FROM TBL_MENU
 ORDER BY MENU_PRICE DESC;  -- 내림차순 DESC 는 생략 불가.
 
  SELECT
       MENU_CODE
	  ,MENU_NAME 
	  ,MENU_PRICE
  FROM TBL_MENU
 ORDER BY MENU_PRICE DESC,
          MENU_NAME ASC;
          
SELECT 
       MENU_CODE
	  ,MENU_PRICE
      ,MENU_CODE * MENU_PRICE
      FROM TBL_MENU
ORDER BY MENU_CODE * MENU_PRICE DESC;

SELECT FIELD('A','A','B','C'); -- 제일 왼쪽 값과 같은 값을 출력한다.
SELECT FIELD('B','A','B','C');

SELECT 
       FIELD(ORDERABLE_STATUS, 'N','Y')
  FROM TBL_MENU;
  
  -- 오름차순 시 NULL 마지막으로
SELECT 
       CATEGORY_CODE
	  ,CATEGORY_NAME
      ,REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE;
 
 SELECT 
       CATEGORY_CODE
	  ,CATEGORY_NAME
      ,REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE IS NULL;
 
 -- 내림차순 시 NULL 마지막으로
  SELECT 
       CATEGORY_CODE
	  ,CATEGORY_NAME
      ,REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE DESC;
 
 -- 내림차순 시 NULL 처음으로
   SELECT 
       CATEGORY_CODE
	  ,CATEGORY_NAME
      ,REF_CATEGORY_CODE
  FROM TBL_CATEGORY
 ORDER BY REF_CATEGORY_CODE IS NULL DESC, REF_CATEGORY_CODE DESC;